# Generated by Django 3.2.12 on 2022-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=3)),
            ],
        ),
    ]
