# Generated by Django 3.2.12 on 2022-03-02 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0002_room_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Departments', '0001_initial'),
        ('Units', '0004_auto_20220301_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Departments.department')),
                ('lecturer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Rooms.room')),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Units.unit')),
            ],
        ),
    ]
