# Generated by Django 3.2.12 on 2022-03-11 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0005_auto_20220311_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 12, 50, 58, 139077)),
        ),
    ]
