# Generated by Django 3.2.12 on 2022-03-11 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0006_alter_lecture_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 37, 32, 814664)),
        ),
    ]
