# Generated by Django 3.2.12 on 2022-03-11 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0008_alter_lecture_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 15, 53, 22, 354978)),
        ),
    ]
