# Generated by Django 3.2.12 on 2022-03-22 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0009_alter_lecture_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 22, 50, 22, 290207)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10),
        ),
    ]
