# Generated by Django 3.2.12 on 2022-03-01 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20220301_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='group',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], default='student', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
