# Generated by Django 3.2.12 on 2022-03-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Users', '0003_auto_20220301_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Departments.department'),
        ),
    ]
