# Generated by Django 3.2.12 on 2022-03-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Users', '0004_newuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Departments.department'),
        ),
    ]
