# Generated by Django 3.2.12 on 2022-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_newuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='group',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=9),
        ),
    ]
