# Generated by Django 3.2.12 on 2022-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='eth_s',
            field=models.IntegerField(null=True),
        ),
    ]
