# Generated by Django 3.2.12 on 2022-03-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_auto_20220302_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_occupied', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='time_occupied',
        ),
        migrations.AddField(
            model_name='room',
            name='time_occupied',
            field=models.ManyToManyField(to='Rooms.Time'),
        ),
    ]
