# Generated by Django 3.2.12 on 2022-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_auto_20220303_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_occupied',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Rooms.Time'),
        ),
    ]
