# Generated by Django 3.2.12 on 2022-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0006_alter_room_time_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_occupied',
            field=models.ManyToManyField(blank=True, default=None, to='Rooms.Time'),
        ),
    ]
