# Generated by Django 3.2.12 on 2022-03-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0008_auto_20220311_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ethernet_sockets',
            new_name='ethernet_ports',
        ),
    ]
