# Generated by Django 3.2.12 on 2022-03-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0009_rename_ethernet_sockets_room_ethernet_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
