# Generated by Django 3.2.12 on 2022-03-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='lecturer',
        ),
    ]
