# Generated by Django 3.2.12 on 2022-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Units', '0003_unit_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(max_length=8),
        ),
    ]
